# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/list
Accept: application/json

###

POST http://localhost:8080/add
Content-Type: application/json

{
  "author": "작성자4",
  "title": "제목4",
  "content": "내용4"
}

###

POST http://localhost:8080/update/2
Content-Type: application/json

{
  "author": "작성자2",
  "title": "수정한제목2",
  "content": "수정한내용2"
}

###

DELETE http://localhost:8080/remove/2
Accept: application/json

###